# Generated by Django 5.2.14 on 2026-06-04 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0002_message'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
        migrations.RenameField(
            model_name='message',
            old_name='date_envoi',
            new_name='date_creation',
        ),
        migrations.RemoveField(
            model_name='message',
            name='destinataire',
        ),
        migrations.RemoveField(
            model_name='message',
            name='expediteur',
        ),
        migrations.RemoveField(
            model_name='message',
            name='lu',
        ),
        migrations.AddField(
            model_name='message',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='nom',
            field=models.CharField(default=111, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='message',
            name='sujet',
            field=models.CharField(max_length=200),
        ),
    ]
