# Generated by Django 5.2.14 on 2026-06-04 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0003_alter_message_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='entreprise',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='message',
            name='numero_de_telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
