# Generated by Django 5.2.14 on 2026-06-04 18:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0004_message_entreprise_message_numero_de_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='entreprise',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='numero_de_telephone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\\\+?\\\\d{9,15}$')]),
        ),
    ]
