# Generated by Django 5.2.14 on 2026-06-04 18:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0005_alter_message_entreprise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='numero_de_telephone',
            field=models.CharField(blank=True, max_length=30, null=True, validators=[django.core.validators.RegexValidator(message='Enter a valid phone number.', regex='^\\+?\\d{9,15}$')]),
        ),
    ]
