# Generated by Django 5.2.14 on 2026-06-04 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0006_alter_message_numero_de_telephone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='numero_de_telephone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
