# Generated by Django 5.2.14 on 2026-06-04 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0007_alter_message_numero_de_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='statut',
            field=models.CharField(choices=[('non_lu', 'Non lu'), ('lu', 'Lu'), ('en_attente', 'En attente')], default='non_lu', max_length=15),
        ),
    ]
