# Generated by Django 5.2.14 on 2026-06-05 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0008_message_statut'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('image_principale', models.ImageField(upload_to='portfolio/')),
                ('technologies', models.TextField()),
                ('lien_projet', models.URLField(blank=True, null=True)),
                ('date_realisation', models.DateField()),
                ('ordre_affichage', models.PositiveIntegerField(default=0)),
                ('est_actif', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='OPTINET.categorie')),
            ],
        ),
    ]
