# Generated by Django 5.2.14 on 2026-06-06 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0010_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='image_principale',
            field=models.ImageField(upload_to='photo/'),
        ),
    ]
