# Generated by Django 5.2.14 on 2026-06-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0011_alter_photo_image_principale'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='titre',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
