# Generated by Django 5.2.14 on 2026-07-05 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0013_contact'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='photo',
            name='prix',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
