# Generated by Django 5.2.14 on 2026-07-07 00:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0014_photo_description_photo_prix'),
    ]

    operations = [
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('prix', models.CharField(blank=True, max_length=100, null=True)),
                ('caracteristiques', models.TextField(blank=True, help_text="Une caractéristique par ligne, au format 'Nom: Valeur'. Ex: Modèle: Galaxy A54 / Réseau: 4G/5G / Batterie: 5000 mAh", null=True)),
                ('est_actif', models.BooleanField(default=True)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordre', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoProduit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='produits/')),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('produit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='OPTINET.produit')),
            ],
            options={
                'ordering': ['-est_principale', 'ordre', 'id'],
            },
        ),
    ]
