# Generated by Django 5.2.14 on 2026-07-07 03:26

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0016_migrer_photos_en_produits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Actualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=255)),
                ('contenu', models.TextField(blank=True, null=True)),
                ('categorie', models.CharField(choices=[('intervention', 'Intervention terrain'), ('realisation', 'Réalisation'), ('actualite', 'Actualité'), ('annonce', 'Annonce & Info')], default='intervention', max_length=20)),
                ('video_url', models.URLField(blank=True, help_text='Lien YouTube (facultatif)', null=True)),
                ('est_publie', models.BooleanField(default=True)),
                ('date_publication', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-date_publication', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhotoActualite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='actualites/')),
                ('est_principale', models.BooleanField(default=False)),
                ('ordre', models.PositiveIntegerField(default=0)),
                ('actualite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='OPTINET.actualite')),
            ],
            options={
                'ordering': ['-est_principale', 'ordre', 'id'],
            },
        ),
    ]
