# Generated by Django 5.2.14 on 2026-07-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0018_actualite_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actualite',
            name='service',
            field=models.CharField(blank=True, choices=[('reseaux', 'Réseaux & Infrastructure'), ('securite', 'Sécurité & Surveillance'), ('fibre', 'Fibre Optique & Télécoms'), ('serveurs', 'Serveurs & Virtualisation'), ('telephonie', "Téléphonie d'Entreprise"), ('conseil', 'Conseil & Formation'), ('developpement', 'Développement & Applications')], help_text="Service OPTINET associé (pour l'afficher sur la page du service)", max_length=20, null=True),
        ),
    ]
