# Generated by Django 5.2.14 on 2026-07-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0021_seed_categories_produits'),
    ]

    operations = [
        migrations.AddField(
            model_name='produit',
            name='quantite_disponible',
            field=models.PositiveIntegerField(blank=True, help_text='Stock disponible (laisser vide si non suivi)', null=True),
        ),
    ]
