# Generated by Django 5.2.14 on 2026-07-11 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0022_produit_quantite_disponible'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageVue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('path', models.CharField(max_length=255)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'path')},
            },
        ),
        migrations.CreateModel(
            name='VisiteurJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('empreinte', models.CharField(max_length=64)),
            ],
            options={
                'unique_together': {('date', 'empreinte')},
            },
        ),
    ]
