# Generated by Django 5.2.14 on 2026-07-11 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OPTINET', '0023_pagevue_visiteurjour'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisiteLive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empreinte', models.CharField(max_length=64, unique=True)),
                ('quand', models.DateTimeField(db_index=True)),
            ],
        ),
        migrations.CreateModel(
            name='DimensionJour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('type', models.CharField(choices=[('source', 'Source'), ('appareil', 'Appareil'), ('navigateur', 'Navigateur'), ('pays', 'Pays')], max_length=12)),
                ('valeur', models.CharField(max_length=120)),
                ('count', models.PositiveIntegerField(default=0)),
            ],
            options={
                'unique_together': {('date', 'type', 'valeur')},
            },
        ),
    ]
